config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'portfolios#index'
  resources :albums, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :album_items, only: [:new, :create, :destroy]
  resources :items, only:  [:index, :show, :new, :edit, :update, :create, :destroy]
  resources :genres, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord

  validates :title, :description, presence: true
  has_many :album_items
  has_many :items, through: :album_items
  belongs_to :user
  

end

app/models/album_item.rb
class AlbumItem < ApplicationRecord
  belongs_to :album
  belongs_to :item
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, :description, presence: true
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord

  validates :title, :url, :description, presence: true

  belongs_to :user
  has_many :album_items
  has_many :albums, through: :album_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true

  has_many :albums
end

app/controllers/album_items_controller.rb
class AlbumItemsController < ApplicationController
  
  def new
    @album = Album.find(params[:format])
    @album_item = AlbumItem.new
    @items = Item.where.not(id: Album.find(params[:format]).items).where(user_id: current_user.id)
  end

  def create
    @album_item = AlbumItem.new(album_item_params)
    if @album_item.save
      redirect_to album_path(@album_item.album_id)
    else
      @items = Item.where(user_id: current_user.id)
      @album = Album.find(params[:album_item][:album_id])
      render :new
    end
  end

  def destroy
    AlbumItem.find_by(album_id: params[:id],item_id: params[:format]).destroy
    redirect_to album_path
  end

  private

  def album_item_params
    params.require(:album_item).permit(:item_id, :album_id)
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = Album.where(user_id: current_user.id)
  end


  def show
    @items = Album.find(params[:id]).items
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to albums_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @album.update(album_params)
      redirect_to album_path
    else
      render :edit
    end
  end

  def destroy
    dels = AlbumItem.where(album_id: @album.id)
    dels.each do |del|
      del.destroy if del
    end
    @album.destroy
    redirect_to albums_path
  end

  private

  def album_params
    params.require(:album).permit(:title, :description).merge(user_id: current_user.id)
  end

  def set_album
    @album = Album.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all.where.not(id: 0)
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to genres_path
    else
      render :new
    end
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to genre_path
    else
      render :edit
    end
  end

  def destroy
    items = Item.where(params[:id])
    unless items == []
      items.each do |item|
        item.update(genre_id: 0)
      end
    end

    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to genres_path

  end

  private

  def genre_params
    params.require(:genre).permit(:name, :description)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action :genres_set
  
  def index
    @items = Item.where(user_id: current_user.id)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to item_path
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])

    dels = AlbumItem.where(item_id: @item.id)
    dels.each do |del|
      del.destroy if del
    end
    @item.destroy
    redirect_to items_path
  end

  

  private

  def item_params
    params.require(:item).permit(:title, :url, :genre_id, :description).merge(user_id: current_user.id)
  end

  def genres_set
    @item = Item.new
    @genres = Genre.all
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
    @albums = Album.where(user_id: current_user.id)
  end
end

app/helpers/album_items_helper.rb
module AlbumItemsHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/album_items/new.html.erb
<main class="main">
  <div class="inner">
  <%= link_to ">トップページへ戻る", root_path%>
  <h1>アルバムに追加</h1>
    <div>
    <%= link_to "キャンセル", album_path(@album.id), class: :nav__btn %>
    </div>
    <%= form_with model: @album_item, local: true do |f| %>
    <div>
    <% if @items == [] %>
    追加できるアイテムがありません
    <% else %>
    <%= f.label :アイテム選択, class: 'item-form__label' %>
    <%= f.collection_select(:item_id, @items, :id, :title, {},{class:"select-box", id:"item-sales-status"}) %>
    </div>

    <%= f.hidden_field :album_id, class: 'album_name album-form__input', value: @album.id %>

    <div>
    <%= f.submit class: :nav__btn %>
    </div>
    <% end %>
    <% end %>
  </div>
</div>
</main>

app/views/albums/edit.html.erb
<main class="main">
  <div class="inner">
  <%= link_to ">トップページへ戻る", root_path%>
  <h1>アルバム編集</h1>
    <%= link_to "キャンセル", album_path(@album.id), class: :nav__btn %>
    <%= form_with(model: @album, method: :patch, local: true) do |f| %>
    <%= f.text_field :title, class: 'album_name album-form__input', placeholder: 'アルバム名を入力してください', value: @album.title %>
    <%= f.text_field :description, class: 'album_name album-form__input', placeholder: '説明を入力してください', value: @album.description %>
    <%= f.submit "変更する" ,class: :nav__btn %>
    <% end %>
  </div>
</div>
</main>

app/views/albums/index.html.erb
<main class="main">
  <div class="inner">
    <%= link_to ">トップページへ戻る", root_path%>
    <div>
      <h1>アルバム一覧</h1>
    </div>
    <%= link_to "アルバム新規作成", new_album_path, class: :nav__btn %>
    <div class="background">
      <% if @albums == [] %>
      アルバムがありません
      <% else %>
        <% @albums.each do |album| %>
          <%= link_to album_path(album.id) do %>
            <div class="card">
              <%= album.title %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</main>

app/views/albums/new.html.erb
<main class="main">
  <div class="inner">
  <%= link_to ">トップページへ戻る", root_path%>
  <h1>新規アルバム</h1>
    <div>
      <%= link_to "キャンセル", albums_path, class: :nav__btn %>
    </div>
    <%= form_with model: @album, local: true do |f|%>
    <div class='album-form__field'>
      <div class='album-form__field--left'>
        <%= f.label :アルバム名, class: 'album-form__label' %>
      </div>
        <div class='album-form__field--right'>
          <%= f.text_field :title, class: 'album_name album-form__input', placeholder: 'アルバム名を入力してください' %>
        </div>
      <div class='album-form__field--left'>
        <%= f.label :説明, class: 'album-form__label' %>
      </div>
        <div class='album-form__field--right'>
          <%= f.text_field :description, class: 'album_name album-form__input', placeholder: '説明を入力してください' %>
        </div>
      </div>
      <div class='album-form__field'>
        <div class='album-form__field--left'>
        </div>
        <div class='album-form__field--right'>
          <%= f.submit class: :nav__btn %>
        </div>
      </div>
        <% end %>
    </div>
</main>

app/views/albums/show.html.erb
<main class="main">
  <div class="inner">
  <div>
  <%= link_to ">トップページへ戻る", root_path%>
  </div>
  <div>
  <%= link_to ">アルバム一覧へ戻る", albums_path%>
  </div>
  <h1>アルバム詳細</h1>
    <%= "アルバム名: #{@album.title}" %>
    <div>
      <div>
      <%= link_to "アルバム削除",album_path, method: :delete, class: :nav__btn %>
      <%= link_to "アルバム編集", edit_album_path, class: :nav__btn %>
      <%= link_to "アイテム登録", new_album_item_path(@album.id), class: :nav__btn %>
      </div>
    </div>

    <div>
    登録アイテム一覧
    </div>

    <div>
      <% @items.each do |item| %>
      <div>
      <%= item.title %>
      <%= link_to item.url, item.url, target: :_blank, rel: "noopener noreferrer" %>
      <%= link_to "登録解除", album_item_path(@album.id, item.id,), method: :delete, class: :nav__btn %>
      </div>
      <% end %>
      
      
    </div>
  </div>
</div>
</main>

app/views/genres/edit.html.erb
<main class="main">
  <div class="inner">
  <%= link_to ">トップページへ戻る", root_path%>
  <h1>ジャンル編集</h1>
    <%= link_to "キャンセル", genre_path(@genre.id), class: :nav__btn %>
    <%= form_with(model: @genre, method: :patch, local: true) do |f| %>
    <div>
    <%= f.text_field :name, placeholder: 'ジャンル名を入力してください', value: @genre.name %>
    </div>
    <div>
    <%= f.text_field :description, placeholder: '説明を入力してください', value: @genre.description %>
    </div>
    <%= f.submit class: :nav__btn %>

    <% end %>
    </div>
  </div>
</main>

app/views/genres/index.html.erb
<main class="main">
  <div class="inner">
    <%= link_to ">トップページへ戻る", root_path%>
    <h1>ジャンル一覧</h1>
    <%= link_to "ジャンル新規作成", new_genre_path, class: :nav__btn %>
      <div class="background">
        <% if @genres == [] %>
          ジャンルがありません。
        <% else %>
          <% @genres.each do |genre| %>
            <%= link_to genre_path(genre.id), method: :get  do %>
              <div class="card">
                <%= genre.name %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
  </div>
</main>

app/views/genres/new.html.erb
<main class="main">
  <div class="inner">
  <%= link_to ">トップページへ戻る", root_path%>
  <h1>ジャンル新規作成</h1>
    <%= link_to "キャンセル", genres_path, class: :nav__btn %>
    <%= form_with(model: @genre, local: true) do |f| %>
    <div>
      <%= f.label :ジャンル名, class: 'item-form__label' %>
      <%= f.text_field :name, class: 'item_name item-form__input', placeholder: 'ジャンル名を入力してください' %>
    </div>
    <div>
      <%= f.label :説明, class: 'item-form__label' %>
      <%= f.text_field :description, class: 'item_name item-form__input', placeholder: '説明を入力してください' %>
    </div>
    <%= f.submit class: :nav__btn %>
    <% end %>
  </div>
</div>
</main>

app/views/genres/show.html.erb
<main class="main">
  <div class="inner">
  <div>
  <%= link_to ">トップページへ戻る", root_path%>
  </div>
  <div>
  <%= link_to ">ジャンル一覧へ戻る", genres_path %>
  </div>
  <h1>ジャンル詳細</h1>
    <div>
      <%= link_to "ジャンル削除", genre_path, method: :delete, class: :nav__btn %>
      <%= link_to "ジャンル編集", edit_genre_path, class: :nav__btn %>
      
    </div>

    <div>
      <%= @genre.name %>
    </div>
</div>
</div>
</main>

app/views/items/edit.html.erb
<main class="main">
  <div class="inner">
  <%= link_to ">トップページへ戻る", root_path%>
  <h1>アイテム編集</h1>
    <%= link_to "キャンセル", item_path(@item.id), class: :nav__btn %>
    <%= form_with(model: @item, method: :patch, local: true) do |f| %>
    <div>
    <%= f.text_field :title, placeholder: 'アイテム名を入力してください', value: @item.title %>
    </div>
    <div>
    <%= f.text_field :url, placeholder: 'URLを入力してください', value: @item.url %>
    </div>
    <div>
    <%= f.collection_select(:genre_id, @genres, :id, :name, {selected: @item.genre_id}, {class:"select-box", id:"item-sales-status"} )%>
    </div>
    <div>
    <%= f.text_field :description, placeholder: '説明を入力してください', value: @item.description %>
    </div>
    <%= f.submit class: :nav__btn %>

    <% end %>
    </div>
  </div>
</main>

app/views/items/index.html.erb
<main class="main">
  <div class="inner">
    <%= link_to ">トップページへ戻る", root_path%>
    <h1>アイテム一覧</h1>
    <%= link_to "アイテム新規作成", new_item_path, class: :nav__btn %>
    <div class="background">
      <% if @items == [] %>
      アイテムがありません
      <% else %>
        <% @items.each do |item| %>
          <%= link_to item_path(item.id), method: :get do %>
            <div class="card">
              <%= item.title%>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</main>

app/views/items/new.html.erb
<main class="main">
  <div class="inner">
  <%= link_to ">トップページへ戻る", root_path%>
  <h1>アイテム新規作成</h1>
    <%= link_to "キャンセル", items_path, class: :nav__btn %>
    <%= form_with(model: @item, local: true) do |f| %>
    <div>
      <%= f.label :アイテム名, class: 'item-form__label' %>
      <%= f.text_field :title, class: 'item_name item-form__input', placeholder: 'アイテム名を入力してください' %>
    </div>
    <div>
      <%= f.label :アイテムURL, class: 'item-form__label' %>
      <%= f.text_field :url, class: 'item_url item-form__input', placeholder: 'URLを入力してください' %>
    </div>
    <div>
      <%= f.label :ジャンル, class: 'item-form__label' %>
      <%= f.collection_select(:genre_id, @genres, :id, :name, {}, {class:"select-box", id:"item-sales-status"} ) %>
    </div>
    <div>
      <%= f.label :説明, class: 'item-form__label' %>
      <%= f.text_field :description, class: 'item_url item-form__input', placeholder: '説明を入力してください' %>
    </div>
    <%= f.submit class: :nav__btn %>
    <% end %>
  </div>
</div>
</main>

app/views/items/show.html.erb
<main class="main">
  <div class="inner">
    <div>
      <%= link_to ">トップページへ戻る", root_path%>
    </div>
    <div>
      <%= link_to ">アイテム一覧へ戻る", items_path %>
    </div>
    <h1>アイテム詳細</h1>
      <div>
        <%= link_to "アイテム削除", item_path, method: :delete, class: :nav__btn %>
        <%= link_to "アイテム編集", edit_item_path, class: :nav__btn %>
      </div>
      <div>
        <%= @item.title %>
      </div>
      <div>
        <%= @item.url %>
      </div>
      <div>
      <% if @genres == [] %>
        ジャンルが存在しません。
        
      <% elsif @genres.find(@item.genre_id) == nil %>
        ジャンルが削除されています。
      <% else %>
        <%= @genres.find(@item.genre_id).name %>
      <% end %>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PortfolioApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
          <%= link_to "PortfolioApp", root_path, class: :logo %>
            <%# <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
            こんにちは<%= current_user.name %>さん
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__btn %>
              <%# <%= link_to "New Album", root_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PortfolioApp All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/portfolios/index.html.erb
<main class="main">

  <div class="inner">
  <h1>トップページ</h1>
    <% if user_signed_in? %>
         <div class="tile_table">
          <%= link_to albums_path do %>
          <div class="tile">
            <div class="tile_content">
              <%= image_tag "icon_album.png"%>
              <%= "アルバム一覧" %>
            </div>
          </div>
        　<% end %>

          <%= link_to items_path do %>
          <div class="tile">
            <div class="tile_content">
              <%= image_tag "icon_item.png"%>
              <%= "アイテム一覧" %>
            </div>
          </div>
          <% end %>

          <%= link_to genres_path do %>
          <div class="tile">
            <div class="tile_content">
              <%= image_tag "icon_genre.png"%>
              <%= "ジャンル一覧" %>
            </div>
          </div>
          <% end %>

        </div>

    <% end %>
  </div>
</main>